version : "3"
volumes:
  kc_postgres_data:
      driver: local

networks:
  web:
    external:
      name: traefik_web

services:
  kc-postgres:
    image: postgres
    volumes:
      - kc_postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
  keycloak:
    image: jboss/keycloak:7.0.1
    container_name: keycloak
    restart: always
    expose:
      - 8180
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: kc-postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    networks:
      - web
    command: |
      -Djboss.socket.binding.port-offset=100
    depends_on:
      - kc-postgres
    tty: true
    labels:
      traefik.enable: true
      traefik.host: keycloak
      traefik.http.routers.keycloak.entrypoints: http
      traefik.http.services.keycloak.loadbalancer.server.port: 8180
      traefik.docker.network: traefik_web