version: '3'
networks:
  web:
    driver: bridge

services:
  reverse-proxy:
    image: traefik:v2.5 # The official Traefik docker image
    ports:
      - "8090:80"     # The HTTP port
      - "8080:8080" # The Web UI (enabled by --api)

    command:
      - --log.level=INFO
      - --api.insecure=true
      - --entrypoints.web.address=:80
      - --providers.docker

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # So that Traefik can listen to the Docker events
      # - ./traefik.yaml:/etc/traefik/traefik.yml
    networks:
      - web
